"""Interactive HTML tutorial generator from manifest data."""

from __future__ import annotations

import html
from pathlib import Path

from demo_video_maker.models import Manifest

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
  .header {{ background: #1e293b; padding: 2rem; text-align: center;
             border-bottom: 1px solid #334155; }}
  .header h1 {{ font-size: 1.75rem; font-weight: 600; }}
  .header .meta {{ color: #94a3b8; margin-top: 0.5rem; font-size: 0.875rem; }}
  .steps {{ max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
  .step {{ background: #1e293b; border-radius: 12px; margin-bottom: 1.5rem;
           overflow: hidden; border: 1px solid #334155; transition: border-color 0.2s; }}
  .step:hover {{ border-color: #3b82f6; }}
  .step-header {{ display: flex; align-items: center; gap: 1rem; padding: 1rem 1.5rem;
                  background: #0f172a; }}
  .step-number {{ background: #3b82f6; color: white; width: 2rem; height: 2rem;
                  border-radius: 50%; display: flex; align-items: center; justify-content: center;
                  font-weight: 700; font-size: 0.875rem; flex-shrink: 0; }}
  .step-narration {{ font-size: 0.95rem; }}
  .step-image {{ width: 100%; display: block; cursor: pointer; }}
  .step-image:hover {{ opacity: 0.95; }}
  .nav {{ display: flex; justify-content: center; gap: 0.5rem; padding: 2rem; flex-wrap: wrap; }}
  .nav button {{ background: #334155; color: #e2e8f0; border: none; padding: 0.5rem 1rem;
                 border-radius: 6px; cursor: pointer; font-size: 0.875rem; }}
  .nav button:hover {{ background: #3b82f6; }}
  .nav button.active {{ background: #3b82f6; }}
  .footer {{ text-align: center; padding: 2rem; color: #64748b; font-size: 0.75rem; }}
  .lightbox {{ display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.9);
               z-index: 100; align-items: center; justify-content: center; cursor: pointer; }}
  .lightbox.show {{ display: flex; }}
  .lightbox img {{ max-width: 95vw; max-height: 95vh; border-radius: 8px; }}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="meta">{step_count} steps</div>
</div>
<div class="steps" id="steps">{steps_html}</div>
<div class="nav" id="nav">{nav_html}</div>
<div class="footer">Generated by demo-video-maker</div>
<div class="lightbox" id="lightbox" onclick="this.classList.remove('show')">
  <img id="lightbox-img" src="" alt="Enlarged screenshot">
</div>
<script>
document.querySelectorAll('.step-image').forEach(img => {{
  img.addEventListener('click', () => {{
    document.getElementById('lightbox-img').src = img.src;
    document.getElementById('lightbox').classList.add('show');
  }});
}});
</script>
</body>
</html>"""


def generate_html_tutorial(manifest: Manifest, output_path: Path) -> Path:
    """Generate an interactive HTML tutorial from the manifest.

    Creates a self-contained HTML file with step-by-step screenshots,
    narration text, navigation buttons, and a lightbox for image zoom.

    Args:
        manifest: Recording manifest with frames and narrations.
        output_path: Path to write the HTML file.

    Returns:
        Path to the created HTML file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    steps_html_parts: list[str] = []
    nav_html_parts: list[str] = []

    for step in manifest.steps:
        frame_rel = Path(step.frame_path).name
        narration_escaped = html.escape(step.narration) if step.narration else ""

        step_html = (
            f'<div class="step" id="step-{step.index}">'
            f'<div class="step-header">'
            f'<div class="step-number">{step.index + 1}</div>'
            f'<div class="step-narration">{narration_escaped}</div>'
            f'</div>'
        )
        img_alt = f"Step {step.index + 1}"
        step_html += f'<img class="step-image" src="frames/{frame_rel}" alt="{img_alt}">'
        step_html += "</div>"
        steps_html_parts.append(step_html)

        nav_html_parts.append(
            f'<button onclick="document.getElementById(\'step-{step.index}\')'
            f'.scrollIntoView({{behavior:\'smooth\'}})">{step.index + 1}</button>'
        )

    rendered = _TEMPLATE.format(
        title=html.escape(manifest.title),
        step_count=len(manifest.steps),
        steps_html="\n".join(steps_html_parts),
        nav_html="\n".join(nav_html_parts),
    )

    output_path.write_text(rendered)
    return output_path
